Repository mozilla-it/ctms-api, pull requests merged in 2023-01, with the labels that each got.

#501 Bump Poetry in Docker
  docker/Dockerfile
  poetry.lock
Labels: dev

#500 Remove all bigquery import machinery
  ctms/bin/load_sample_csv.py
  ctms/bin/prepare_csvs.py
  ctms/bin/report_duplicates.py
  ctms/bin/sync_bq_tables.py
  ctms/csv_helpers.py
  ctms/schemas/__init__.py
  ctms/schemas/addons.py
  ctms/schemas/email.py
  ctms/schemas/fxa.py
  ctms/schemas/newsletter.py
  ctms/schemas/relay.py
  ctms/schemas/vpn.py
  poetry.lock
  pyproject.toml
  scripts/importers/copy_to_db.sh
  scripts/importers/finish.sql
  scripts/importers/import-mofo.sql
  scripts/importers/setup.sql
  tests/data/good_csvs/CTMS_SAMPLE_contact_to_amo.csv
  tests/data/good_csvs/CTMS_SAMPLE_contact_to_email.csv
  tests/data/good_csvs/CTMS_SAMPLE_contact_to_fxa.csv
  tests/data/good_csvs/CTMS_SAMPLE_contact_to_newsletter.csv
  tests/data/good_csvs/CTMS_SAMPLE_contact_to_vpn_waitlist.csv
  tests/data/good_csvs/CTMS_SAMPLE_email_ids.csv
  tests/data/good_csvs/duplicates.txt
  tests/data/good_csvs_no_amo/CTMS_SAMPLE_contact_to_amo.csv
  tests/data/good_csvs_no_amo/CTMS_SAMPLE_contact_to_email.csv
  tests/data/good_csvs_no_amo/CTMS_SAMPLE_contact_to_fxa.csv
  tests/data/good_csvs_no_amo/CTMS_SAMPLE_contact_to_newsletter.csv
  tests/data/good_csvs_no_amo/CTMS_SAMPLE_contact_to_vpn_waitlist.csv
  tests/data/good_csvs_no_amo/CTMS_SAMPLE_email_ids.csv
  tests/data/good_csvs_no_amo/duplicates.txt
  tests/unit/test_bin_load_sample_csv.py
  tests/unit/test_ingest.py
Labels: dev

#503 Always run container with single Uvicorn process
  asgi.py
  ctms/app.py
  ctms/config.py
  ctms/log.py
  ctms/metrics.py
  docker/Dockerfile
  docker/docker-entrypoint.sh
  docker/gunicorn_conf.py
  docs/configuration.md
  poetry.lock
  pyproject.toml
  tests/unit/test_log.py
  tests/unit/test_metrics.py
Labels: dev

#508 Move testing outside Docker, simplify Dockerfile
  .github/workflows/test-build.yaml
  .secrets.baseline
  Makefile
  README.md
  bin/test.sh
  bin/update_and_install_system_packages.sh
  bin/update_baseline.sh
  docker-compose.yaml
  docker/Dockerfile
  docker/test.sh
  docs/developer_setup.md
  docs/testing_strategy.md
  scripts/update_baseline.sh
Labels: docker

#492 Fix #469: implement waitlists as generic relationship
  ctms/acoustic_service.py
  ctms/app.py
  ctms/backport_legacy_waitlists.py
  ctms/crud.py
  ctms/database.py
  ctms/ingest.py
  ctms/metrics.py
  ctms/models.py
  ctms/schemas/__init__.py
  ctms/schemas/contact.py
  ctms/schemas/relay.py
  ctms/schemas/vpn.py
  ctms/schemas/waitlist.py
  docs/adrs/waitlists_relationships.md
  migrations/versions/20221213_9c37ea9b5bba_add_waitlist_table.py
  migrations/versions/20221220_e446b56f38e1_remove_vpn_waitlist_field_and_table.py
  migrations/versions/20221222_4f6c48142631_remove_relay_waitlist_field_and_table.py
  tests/unit/conftest.py
  tests/unit/sample_data.py
  tests/unit/test_acoustic_service.py
  tests/unit/test_api.py
  tests/unit/test_api_get.py
  tests/unit/test_api_patch.py
  tests/unit/test_backport_legacy_waitlists.py
  tests/unit/test_bulk.py
  tests/unit/test_crud.py
  tests/unit/test_metrics.py
  tests/unit/test_schema_contact.py
  tests/unit/test_schema_waitlist.py
Labels: enhancement

#520 Remove SQL assertions
  tests/unit/test_crud.py
  tests/unit/test_ingest_stripe.py
Labels: python

#510 Streamline environment bootstrapping, move contents of `docker/` to top level
  .env.example
  .github/workflows/build-image.yaml
  .github/workflows/test-build.yaml
  .gitignore
  .secrets.baseline
  Dockerfile
  Makefile
  bin/update_baseline.sh
  docker-compose.yaml
  docker/config/env.dist
  docker/config/local_dev.env
  docker/log_config.json
  docs/configuration.md
  pyproject.toml
Labels: dev

#522 Align versions of Python@3.10.9 and Poetry@1.3.2
  .github/workflows/lint.yaml
  .github/workflows/test-build.yaml
  .secrets.baseline
  Dockerfile
  docs/developer_setup.md
  poetry.lock
  pyproject.toml
Labels: dependencies, docker
