Repository mozilla-it/ctms-api, pull requests merged in 2023-07, with the labels that each got.

#728 Add template and number prefix to ADRs docs
  docs/adrs/001-madr-fxa-ctms.md
  docs/adrs/002-waitlists_relationships.md
  docs/adrs/template.md
Labels: documentation

#707 Add `subscribed`/`unsub_reason` fields to waitlist
  Makefile
  bin/integration-test.sh
  ctms/crud.py
  ctms/models.py
  ctms/schemas/contact.py
  ctms/schemas/waitlist.py
  docs/adrs/waitlists_subscribed.md
  migrations/versions/20230619_2a0489304e03_add_subscribed_unsub_reason_to_waitlist.py
  tests/factories/models.py
  tests/integration/test_basket_waitlist_subscription.py
  tests/unit/conftest.py
  tests/unit/routers/contacts/test_api_get.py
  tests/unit/routers/contacts/test_api_patch.py
  tests/unit/test_backport_legacy_waitlists.py
Labels: enhancement

#738 Pin Basket to 2023-04-24
  docker-compose.yaml
Labels: internal-change

#736 Fix database migration history
  migrations/versions/20230629_5bfd08b53489_create_update_timestamp_mixin.py
Labels: internal-change

#739 Delete AWS build + deploy workflow
  .github/workflows/build-image.yaml
Labels: deploy, internal-change

#744 Combine CI checks into one workflow
  .github/workflows/ci.yaml
  .github/workflows/dependabot-automerge.yaml
  .github/workflows/integration-test.yaml
  .github/workflows/lint.yaml
  .github/workflows/test-build.yaml
  .secrets.baseline
Labels: internal-change

#737 Assign update timestamps at database level
  ctms/crud.py
  ctms/schemas/__init__.py
  ctms/schemas/newsletter.py
  ctms/schemas/waitlist.py
  tests/unit/test_crud.py
Labels: internal-change

#745 Fix #733: fix replacing the list of waitlists in PUT requests
  ctms/backport_legacy_waitlists.py
  ctms/crud.py
  docs/adrs/004-waitlists_subscribed.md
  tests/unit/conftest.py
  tests/unit/routers/contacts/test_api.py
  tests/unit/test_crud.py
Labels: bug

#755 Slim down developer docs
  .secrets.baseline
  docs/developer_setup.md
Labels: documentation

#757 Ref #681: Improve quality standards
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
  ctms/monitor.py
  ctms/routers/platform.py
  docs/README.md
  docs/developer_setup.md
  docs/testing_strategy.md
Labels: documentation

#753 Fix #605: Adjust Basket integration test and workflow docs
  docs/diagrams/bedrock_basket_ctms_acoustic.md
  tests/integration/test_basket_waitlist_subscription.py
Labels: documentation

#758 Fix #662: remove deployment docs
  docs/deployment_guide.md
Labels: documentation

#760 Untangle simplify and fix heartbeat code
  ctms/acoustic_service.py
  ctms/app.py
  ctms/config.py
  ctms/crud.py
  ctms/exception_capture.py
  ctms/monitor.py
  ctms/routers/platform.py
  tests/unit/routers/test_platform.py
Labels: bug, internal-change

#762 Fix #761: fix waitlist boolean data type
  .secrets.baseline
  ctms/acoustic_service.py
  tests/unit/test_acoustic_service.py
Labels: bug

#768 Use timestamps instead of dates in Acoustic records
  ctms/acoustic_service.py
  tests/unit/test_acoustic_service.py
Labels: bug, internal-change

#759 Fix #642: count total number of contacts
  ctms/crud.py
  ctms/metrics.py
  ctms/routers/platform.py
  tests/unit/test_crud.py
  tests/unit/test_metrics.py
Labels: enhancement

#752 Fix #562: add subscribed field to newsletters Acoustic relational table
  ctms/acoustic_service.py
  tests/unit/test_acoustic_service.py
Labels: enhancement

#777 Follow-up #562: fix bool column conversion
  ctms/acoustic_service.py
  tests/unit/test_acoustic_service.py
Labels: bug

#770 Remove notion of `trivial` logs
  ctms/app.py
  ctms/bin/acoustic_sync.py
  ctms/log.py
  ctms/routers/platform.py
  docs/deployment_guide.md
  tests/unit/bin/test_acoustic_sync.py
  tests/unit/routers/test_platform.py
Labels: internal-change

#772 Send StreamHandler loggers to stdout
  ctms/log.py
Labels: internal-change

#779 Fix #778: switch newsletters timestamps columns to date and time
  ctms/acoustic_service.py
  tests/unit/test_acoustic_service.py
Labels: enhancement
