Repository mozilla-it/ctms-api, pull requests merged in 2023-02, with the labels that each got.

#532 Bump Python to 3.11.1
  .github/workflows/lint.yaml
  .github/workflows/test-build.yaml
  Dockerfile
  ctms/app.py
  ctms/ingest.py
  ctms/sync.py
  poetry.lock
  pyproject.toml
Labels: dev, dependencies, python

#530 Ref #469: Unsubscribe from `vpn` waitlist when unsubscribing from `guardian-vpn-waitlist` newsletter
  ctms/backport_legacy_waitlists.py
  tests/unit/test_api_patch.py
Labels: bug

#538 Run formatting black 23.1.0
  ctms/bin/client_credentials.py
  ctms/crud.py
  ctms/ingest_stripe.py
  ctms/schemas/mofo.py
  tests/unit/test_acoustic_service.py
Labels: dependencies

#546 Fix #545: allow empty string in waitlist platform field
  ctms/schemas/waitlist.py
  tests/unit/test_schema_waitlist.py
Labels: bug

#547 Fix #507: relax source URL validation
  ctms/schemas/newsletter.py
  tests/unit/test_schema_contact.py
Labels: bug

#548 Fix #240, #529: Add GDPR deletion endpoint
  ctms/app.py
  ctms/bin/gdpr
  ctms/crud.py
  tests/unit/test_api.py
  tests/unit/test_api_delete.py
  tests/unit/test_metrics.py
Labels: enhancement

#551 Ref #548: make basket_token field optional in contact responses body
  ctms/schemas/contact.py
  tests/unit/conftest.py
  tests/unit/sample_data.py
  tests/unit/test_api_delete.py
Labels: bug
