Repository mozilla-it/ctms-api, pull requests merged in 2023-04, with the labels that each got.

#570 Add basket / CTMS integration test
  .github/workflows/integration-test.yaml
  Makefile
  bin/integration-test.sh
  bin/lint.sh
  docker-compose.yaml
  poetry.lock
  pyproject.toml
  tests/integration/basket-db-init.sql
  tests/integration/basket.env
  tests/integration/ctms-db-init.sql
  tests/integration/test_basket_waitlist_subscription.py
Labels: dev

#628 Replace most sample data with pytest fixtures
  tests/unit/conftest.py
  tests/unit/sample_data.py
  tests/unit/test_api.py
  tests/unit/test_api_get_by_alt_id.py
  tests/unit/test_api_patch.py
  tests/unit/test_api_post.py
  tests/unit/test_api_put.py
  tests/unit/test_backport_legacy_waitlists.py
  tests/unit/test_bin_acoustic_resync.py
  tests/unit/test_private_api.py
  tests/unit/test_schema_contact.py
Labels: enhancement

#629 Migrate `SAMPLE_STRIPE_DATA` to pytest fixtures
  .secrets.baseline
  tests/unit/conftest.py
  tests/unit/sample_data.py
  tests/unit/test_api_stripe.py
  tests/unit/test_auth.py
  tests/unit/test_crud.py
  tests/unit/test_ingest_stripe.py
Labels: dev

#631 Fix #630: allow 'geo' field to be None or missing in waitlists
  ctms/schemas/waitlist.py
  tests/unit/test_api_get.py
  tests/unit/test_schema_waitlist.py
Labels: bug

#632 Finish moving Stripe data out of `sample_data.py`
  tests/unit/conftest.py
  tests/unit/sample_data.py
  tests/unit/test_api_stripe.py
  tests/unit/test_crud.py
  tests/unit/test_ingest_stripe.py
Labels: dev

#644 Adjust integration tests to Basket changes, fix bugs
  Makefile
  ctms/backport_legacy_waitlists.py
  ctms/schemas/contact.py
  tests/integration/basket-db-init.sql
  tests/integration/test_basket_waitlist_subscription.py
  tests/unit/test_api_patch.py
Labels: bug, dev

#634 Create Stripe customer factories, use in tests
  tests/data/__init__.py
  tests/factories/__init__.py
  tests/factories/models.py
  tests/factories/stripe.py
  tests/unit/conftest.py
  tests/unit/factories.py
  tests/unit/test_api_stripe.py
  tests/unit/test_auth.py
  tests/unit/test_crud.py
  tests/unit/test_ingest_stripe.py
Labels: dev

#639 Bump integration test `timeout-minutes` from 5 to 10
  .github/workflows/integration-test.yaml
Labels: bug

#648 Fix #647: fix bulk update for pending records
  ctms/bin/acoustic.py
  ctms/crud.py
  tests/unit/test_bin_acoustic_resync.py
Labels: bug

#643 Remove Cinchy from overview diagram
  docs/diagrams/ctms_general_overview.svg
Labels: documentation
