Repository mozilla-it/ctms-api, pull requests merged in 2023-06, with the labels that each got.

#693 Add Dependabot automation workflow
  .github/workflows/dependabot-automerge.yaml
Labels: enhancement

#695 Configure Dependabot to check root dir for Docker
  .github/dependabot.yml
Labels: dependencies

#703 Migrate integration tests to MariaDB v11
  bin/integration-test.sh
  docker-compose.yaml
Labels: dependencies

#686 Ref #565: export contacts database as CSV
  ctms/bin/acoustic.py
  ctms/crud.py
Labels: enhancement

#704 Ref #686: follow-up, remove useless condition
  ctms/bin/acoustic.py
Labels: enhancement

#716 Split `app.py` file into separate routers
  .secrets.baseline
  asgi.py
  ctms/app.py
  ctms/database.py
  ctms/dependencies.py
  ctms/metrics.py
  ctms/routers/__init__.py
  ctms/routers/contacts.py
  ctms/routers/platform.py
  ctms/routers/stripe.py
  tests/unit/bin/test_acoustic.py
  tests/unit/bin/test_acoustic_sync.py
  tests/unit/bin/test_client_credentials.py
  tests/unit/bin/test_healthcheck_sync.py
  tests/unit/conftest.py
  tests/unit/routers/__init__.py
  tests/unit/routers/contacts/__init__.py
  tests/unit/routers/contacts/test_api.py
  tests/unit/routers/contacts/test_api_delete.py
  tests/unit/routers/contacts/test_api_get.py
  tests/unit/routers/contacts/test_api_get_by_alt_id.py
  tests/unit/routers/contacts/test_api_patch.py
  tests/unit/routers/contacts/test_api_post.py
  tests/unit/routers/contacts/test_api_put.py
  tests/unit/routers/contacts/test_bulk.py
  tests/unit/routers/contacts/test_private_api.py
  tests/unit/routers/test_platform.py
  tests/unit/routers/test_stripe.py
  tests/unit/test_app.py
  tests/unit/test_auth.py
  tests/unit/test_metrics.py
Labels: internal-change

#717 Fix #709: use two passes to produce CSV dump
  ctms/bin/acoustic.py
  tests/unit/bin/test_acoustic.py
Labels: bug

#718 Allow for more testing flexibility for local dev
  Makefile
  bin/test.sh
Labels: internal-change

#711 Fix #611: `ContactSchema` now reflects what is stored in database
  ctms/acoustic_service.py
  ctms/crud.py
  ctms/schemas/__init__.py
  ctms/schemas/contact.py
  ctms/schemas/newsletter.py
  tests/unit/conftest.py
  tests/unit/routers/contacts/test_api.py
  tests/unit/routers/contacts/test_api_patch.py
  tests/unit/routers/contacts/test_bulk.py
  tests/unit/test_acoustic_service.py
  tests/unit/test_backport_legacy_waitlists.py
  tests/unit/test_crud.py
Labels: internal-change

#721 Ref #711: follow-up after schema cleanup
  ctms/schemas/contact.py
Labels: internal-change

#720 Delete test for waitlist migrations
  tests/unit/test_backport_legacy_waitlists.py
Labels: internal-change

#724 Start to remove most contact fixtures
  tests/factories/models.py
  tests/unit/schemas/test_contact.py
  tests/unit/schemas/test_newsletter.py
  tests/unit/schemas/test_waitlist.py
  tests/unit/test_crud.py
  tests/unit/test_schema_contact.py
Labels: internal-change

#725 Refactor Acoustic crud tests
  tests/factories/models.py
  tests/unit/conftest.py
  tests/unit/test_crud.py
Labels: internal-change
