Repository mozilla-it/ctms-api, pull requests merged in 2023-03, with the labels that each got.

#567 Force UTC at SQLAlchemy client/session level
  tests/unit/conftest.py
Labels: dev

#568 Add `make format` command
  .secrets.baseline
  Makefile
  bin/lint.sh
Labels: dev

#573 Fix #493: add request id to MozLog
  ctms/app.py
  ctms/log.py
  tests/unit/test_log.py
Labels: enhancement

#566 Do not enforce Python patch version
  poetry.lock
  pyproject.toml
Labels: python

#553 Fix #523: Remove SqlAlchemy 2.0 warnings
  ctms/crud.py
  ctms/models.py
  tests/unit/conftest.py
  tests/unit/test_backport_legacy_waitlists.py
Labels: enhancement

#554 Start to use factories to generate test data
  ctms/database.py
  poetry.lock
  pyproject.toml
  tests/unit/__init__.py
  tests/unit/conftest.py
  tests/unit/factories.py
  tests/unit/test_api_get.py
  tests/unit/test_api_patch.py
Labels: enhancement

#585 Rename the `gdpr` command to `delete_bulk.py`
  ctms/bin/delete_bulk.py
  docs/deployment_guide.md
Labels: enhancement

#569 Ref #565: CTMS-146: Add a way to force Acoustic resync of a list of contacts
  ctms/bin/acoustic.py
  ctms/bin/delete_bulk.py
  ctms/crud.py
  docs/deployment_guide.md
  tests/unit/conftest.py
  tests/unit/factories.py
  tests/unit/test_bin_acoustic_resync.py
  tests/unit/test_crud.py
Labels: enhancement

#586 Migrate `acoustic_*.py` scripts by `acoustic.py` subcommands
  ctms/bin/acoustic.py
  ctms/bin/acoustic_fields.py
  ctms/bin/acoustic_newsletters_mapping.py
  docs/deployment_guide.md
Labels: enhancement

#588 Ref #565: Reset `retry` status from `acoustic.py resync` command
  ctms/bin/acoustic.py
  ctms/crud.py
  tests/unit/test_bin_acoustic_resync.py
Labels: enhancement

#587 Fix #581: polish sync logging and store last error in DB
  .secrets.baseline
  ctms/acoustic_service.py
  ctms/background_metrics.py
  ctms/bin/add_stripe_data_to_acoustic_queue.py
  ctms/bin/flatten_subscriptions_from_firestore_export.py
  ctms/bin/ingest_stripe_data.py
  ctms/crud.py
  ctms/models.py
  ctms/sync.py
  migrations/versions/20230314_a016433d3e8b_add_last_error_message_to_.py
  tests/unit/test_acoustic_service.py
  tests/unit/test_crud.py
  tests/unit/test_sync.py
Labels: enhancement

#597 Add tests for Acoustic field crud functions
  ctms/crud.py
  tests/unit/test_crud.py
Labels: enhancement
