Repository mozilla-it/ctms-api, pull requests merged in 2024-10, with the labels that each got.

#975 Remove more fixtures
  tests/factories/models.py
  tests/unit/conftest.py
  tests/unit/routers/contacts/test_api.py
  tests/unit/routers/contacts/test_api_get.py
  tests/unit/routers/contacts/test_api_patch.py
  tests/unit/routers/contacts/test_api_put.py
  tests/unit/routers/contacts/test_private_api.py
  tests/unit/test_crud.py
Labels: enhancement

#978 Get rid of Dockerfile syntax warning
  Dockerfile
Labels: enhancement

#979 Fix #238: migration to backport prod index
  ctms/models.py
  migrations/versions/20241008_fd04e56b249e_add_uniqueness_to_index.py
Labels: enhancement

#984 Add workflow to build + push image to GAR from this repo
  .github/workflows/build.yaml
Labels: deploy, docker

#994 Fix #742: Update integration tests to use recent basket image
  docker-compose.yaml
  tests/integration/basket.env
Labels: internal-change
