Repository mozilla-it/ctms-api, pull requests merged in 2024-08, with the labels that each got.

#948 Replace `black`, `isort`, and `pylint` with `ruff`
  .pre-commit-config.yaml
  Makefile
  bin/lint.sh
  ctms/backport_legacy_waitlists.py
  ctms/bin/client_credentials.py
  ctms/bin/delete_bulk.py
  ctms/crud.py
  ctms/exception_capture.py
  ctms/metrics.py
  ctms/models.py
  ctms/routers/contacts.py
  ctms/schemas/bulk.py
  ctms/schemas/contact.py
  ctms/schemas/waitlist.py
  poetry.lock
  pyproject.toml
  tests/factories/models.py
  tests/unit/conftest.py
  tests/unit/test_backport_legacy_waitlists.py
  tests/unit/test_crud.py
  tests/unit/test_log.py
Labels: internal-change

#951 Configure factories to automatically commit when called
  tests/factories/models.py
  tests/unit/conftest.py
  tests/unit/routers/contacts/test_api.py
  tests/unit/routers/contacts/test_api_delete.py
  tests/unit/routers/contacts/test_api_get.py
  tests/unit/routers/contacts/test_api_get_by_alt_id.py
  tests/unit/routers/contacts/test_api_patch.py
  tests/unit/routers/contacts/test_bulk.py
  tests/unit/routers/contacts/test_private_api.py
  tests/unit/schemas/test_contact.py
  tests/unit/schemas/test_newsletter.py
  tests/unit/test_auth.py
  tests/unit/test_backport_legacy_waitlists.py
  tests/unit/test_crud.py
  tests/unit/test_log.py
  tests/unit/test_metrics.py
Labels: internal-change

#956 Switch `docker-compose` to `docker compose`
  .env.example
  .github/workflows/ci.yaml
  .secrets.baseline
  Makefile
  bin/integration-test.sh
  bin/test.sh
  docker-compose.yaml
  docs/configuration.md
  docs/developer_setup.md
Labels: dev

#722 Ref #492, Fix #734: drop write support of legacy `vpn_waitlist` and `relay_waitlist` fields
  ctms/backport_legacy_waitlists.py
  ctms/crud.py
  ctms/metrics.py
  ctms/schemas/__init__.py
  ctms/schemas/contact.py
  ctms/schemas/waitlist.py
  tests/unit/routers/contacts/test_api_patch.py
  tests/unit/test_backport_legacy_waitlists.py
  tests/unit/test_metrics.py
Labels: breaking-change, internal-change

#950 Make code changes to address all test warnings
  ctms/app.py
  ctms/auth.py
  ctms/config.py
  ctms/exception_capture.py
  poetry.lock
  pyproject.toml
  tests/unit/routers/contacts/test_api_patch.py
  tests/unit/routers/contacts/test_private_api.py
  tests/unit/test_auth.py
  tests/unit/test_log.py
Labels: internal-change

#958 Rewrite `POST` and `PUT` tests
  Makefile
  ctms/models.py
  migrations/versions/20240807_3689b813fe22_default_email_id_on_insert.py
  tests/factories/models.py
  tests/unit/routers/contacts/test_api_post.py
  tests/unit/routers/contacts/test_api_put.py
Labels: internal-change
